wip

diff --git a/.github/workflows/hive.yml b/.github/workflows/hive.yml
--- a/.github/workflows/hive.yml
+++ b/.github/workflows/hive.yml
@@ -70,8 +70,8 @@ jobs:
         # https://github.com/paradigmxyz/reth/issues/8579
         # ethereum/rpc to be deprecated:
         # https://github.com/ethereum/hive/pull/1117
-        # sim: [smoke/genesis, smoke/network, ethereum/sync]
-        sim: [smoke/genesis, smoke/network]
+        sim: [smoke/genesis, smoke/network, ethereum/sync]
+        # sim: [smoke/genesis, smoke/network]
         include:
           - sim: devp2p
             limit: discv4
@@ -100,8 +100,8 @@ jobs:
             limit: engine-exchange-capabilities
           # TODO: enable engine-withdrawals once resolved:
           # https://github.com/paradigmxyz/reth/issues/8732
-          # - sim: ethereum/engine
-          #   limit: engine-withdrawals
+          - sim: ethereum/engine
+            limit: engine-withdrawals
           - sim: ethereum/engine
             limit: engine-auth
           - sim: ethereum/engine
@@ -109,15 +109,15 @@ jobs:
           # TODO: enable engine-api once resolved:
           # https://github.com/paradigmxyz/reth/issues/8305
           # https://github.com/paradigmxyz/reth/issues/6217
-          # - sim: ethereum/engine
-          #   limit: engine-api
+          - sim: ethereum/engine
+            limit: engine-api
           # TODO: enable cancun once resolved:
           # https://github.com/paradigmxyz/reth/issues/8305
           # https://github.com/paradigmxyz/reth/issues/6217
           # https://github.com/paradigmxyz/reth/issues/8306
           # https://github.com/paradigmxyz/reth/issues/7144
-          # - sim: ethereum/engine
-          #   limit: cancun
+          - sim: ethereum/engine
+            limit: cancun
           # eth_ rpc methods
           - sim: ethereum/rpc-compat
             include:
@@ -142,8 +142,8 @@ jobs:
           # https://github.com/paradigmxyz/reth/issues/7015
           # https://github.com/paradigmxyz/reth/issues/6332
           # debug_ rpc methods
-          # - sim: ethereum/rpc-compat
-          # include: [debug_]
+          - sim: ethereum/rpc-compat
+            include: [debug_]
           # Pyspec cancun jobs
           - sim: pyspec
             include: [cancun/eip4844]
@@ -209,30 +209,35 @@ jobs:
       - name: Run ${{ matrix.sim }} simulator
         run: |
           cd hivetests
-          hive --sim "${{ matrix.sim }}$" --sim.limit "${{matrix.limit}}/${{join(matrix.include, '|')}}" --client reth
+          hive --sim "${{ matrix.sim }}$" --sim.limit "${{matrix.limit}}/${{join(matrix.include, '|')}}" --client reth || true
 
-      - name: Create github issue if sim failed
-        env:
-          GH_TOKEN: ${{ github.token }}
-        if: ${{ failure() }}
+      # - name: Create github issue if sim failed
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
+      #   if: ${{ failure() }}
+      #   run: |
+      #     echo "Simulator failed, creating issue"
+      #     # Check if issue already exists
+      #     # get all issues with the label C-hivetest, loop over each page and check if the issue already exists
+
+      #     existing_issues=$(gh api /repos/paradigmxyz/reth/issues -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -F "labels=C-hivetest" --method GET | jq '.[].title')
+      #     if [[ $existing_issues == *"Hive Test Failure: ${{ matrix.sim }}"* ]]; then
+      #       echo "Issue already exists"
+      #       exit 0
+      #     fi
+      #     gh api \
+      #       --method POST \
+      #       -H "Accept: application/vnd.github+json" \
+      #       -H "X-GitHub-Api-Version: 2022-11-28" \
+      #       /repos/${{ github.repository }}/issues \
+      #       -f title='Hive Test Failure: ${{ matrix.sim }}' \
+      #       -f body="!!!!!!! This is an automated issue created by the hive test failure !!!!!!!<br /><br />The hive test for ${{ matrix.sim }} failed. Please investigate and fix the issue.<br /><br />[Link to the failed run](https://github.com/paradigmxyz/reth/actions/runs/${{ github.run_id }})" \
+      #       -f "labels[]=C-hivetest"
+      
+      - name: Parse hive output
         run: |
-          echo "Simulator failed, creating issue"
-          # Check if issue already exists
-          # get all issues with the label C-hivetest, loop over each page and check if the issue already exists
+          find hivetests/workspace/logs -type f -name "*.json" ! -name "hive.json" -exec python .github/assets/parse.py {} --exclusion .github/assets/hive_exclusion.json +
 
-          existing_issues=$(gh api /repos/paradigmxyz/reth/issues -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -F "labels=C-hivetest" --method GET | jq '.[].title')
-          if [[ $existing_issues == *"Hive Test Failure: ${{ matrix.sim }}"* ]]; then
-            echo "Issue already exists"
-            exit 0
-          fi
-          gh api \
-            --method POST \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/${{ github.repository }}/issues \
-            -f title='Hive Test Failure: ${{ matrix.sim }}' \
-            -f body="!!!!!!! This is an automated issue created by the hive test failure !!!!!!!<br /><br />The hive test for ${{ matrix.sim }} failed. Please investigate and fix the issue.<br /><br />[Link to the failed run](https://github.com/paradigmxyz/reth/actions/runs/${{ github.run_id }})" \
-            -f "labels[]=C-hivetest"
       - name: Print simulator output
         if: ${{ failure() }}
         run: |
